const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=path.join(__dirname,'.local-shares'),attempts=new Map();
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const chunk of req){s+=chunk;if(s.length>8e6)throw Error('size')}return JSON.parse(s)}
module.exports=async function(req,res){const url=new URL(req.url,'http://127.0.0.1');if(!url.pathname.startsWith('/api/shares')&&!url.pathname.startsWith('/s/'))return false;
try{if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`){json(res,403,{error:'访问来源不允许'});return true}
if(url.pathname==='/api/shares'&&req.method==='POST'){const b=await body(req);if(!b.snapshot?.name||!Array.isArray(b.snapshot.scenes)||!['public','password'].includes(b.access)||b.access==='password'&&!/^[A-Za-z0-9]{5,8}$/.test(b.password||'')){json(res,400,{error:'密码需为 5–8 位字母或数字'});return true}if(b.validFor!==undefined&&(!Number.isFinite(b.validFor)||b.validFor<0||b.validFor>31536000)){json(res,400,{error:'有效期不正确'});return true}const id=crypto.randomBytes(24).toString('base64url'),salt=crypto.randomBytes(16).toString('hex'),record={snapshot:b.snapshot,access:b.access,created:Date.now(),expiresAt:b.validFor===0?null:Date.now()+(b.validFor||604800)*1000,once:b.once===true,salt};if(b.access==='password')record.hash=crypto.scryptSync(b.password,salt,32).toString('hex');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.json'),JSON.stringify(record));json(res,201,{path:'/s/'+id,expiresAt:record.expiresAt});return true}
const match=url.pathname.match(/^\/(?:s|api\/shares)\/([A-Za-z0-9_-]{32})(?:\/(open))?$/);if(!match){json(res,404,{error:'分享不存在'});return true}const file=path.join(dir,match[1]+'.json');if(!fs.existsSync(file)){json(res,404,{error:'分享不存在'});return true}const record=JSON.parse(fs.readFileSync(file,'utf8'));
if(record.expiresAt&&Date.now()>=record.expiresAt){json(res,410,{error:'分享已过期，无法访问'});return true}
if(url.pathname.startsWith('/s/')&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'});res.end(page(match[1],record.access==='password'));return true}
if(match[2]==='open'&&req.method==='POST'){if(record.access==='password'){const key=match[1]+req.socket.remoteAddress,now=Date.now(),state=attempts.get(key)||{count:0,until:now+60000};if(now>state.until){state.count=0;state.until=now+60000}if(state.count>=5){json(res,429,{error:'尝试次数较多，请一分钟后重试'});return true}const b=await body(req),candidate=crypto.scryptSync(String(b.password||'').slice(0,64),record.salt,32);if(!crypto.timingSafeEqual(candidate,Buffer.from(record.hash,'hex'))){state.count++;attempts.set(key,state);json(res,403,{error:'密码不正确'});return true}attempts.delete(key)}if(record.once){const latest=JSON.parse(fs.readFileSync(file,'utf8'));if(latest.usedAt){json(res,410,{error:'该分享仅可访问一次，已被查看'});return true}latest.usedAt=Date.now();fs.writeFileSync(file,JSON.stringify(latest))}json(res,200,record.snapshot);return true}json(res,405,{error:'请求方式不支持'});return true}catch{json(res,400,{error:'分享处理失败，请重试'});return true}};
function page(id,locked){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>一隅 · 分享收藏</title><style>body{font:15px system-ui;background:#f5f6f2;color:#303a34}main{max-width:960px;margin:60px auto;padding:24px}article{background:white;padding:20px;margin:16px 0;border-radius:12px}a{display:block;padding:12px 0;color:inherit;text-decoration:none}small{display:block;color:#81877e;margin-top:5px}input,button{padding:12px;border:1px solid #d7ddd3;border-radius:8px}button{background:#46614c;color:white}#error{color:#a55}</style><main><h1>分享收藏</h1><form id="unlock" ${locked?'':'hidden'}><p>输入访问密码</p><input type="password" maxlength="8" required aria-label="访问密码"><button>查看收藏</button></form><p id="error" role="alert"></p><div id="content"></div></main><script>const form=document.querySelector('form');function node(t,v,p){const e=document.createElement(t);e.textContent=v;p.append(e);return e}async function open(password){try{const r=await fetch('/api/shares/${id}/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await r.json();if(!r.ok)throw Error(data.error);const root=document.getElementById('content');root.replaceChildren();node('h1',data.name,root);for(const s of data.scenes){node('h2',s.name,root);for(const g of s.groups){const article=node('article','',root);node('h3',g.name,article);for(const i of g.items){let u;try{u=new URL(i[1]);if(!['https:','http:'].includes(u.protocol))continue}catch{continue}const a=node('a',i[0],article);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';node('small',i[2]||u.hostname,a)}}}form.hidden=true;document.getElementById('error').textContent=''}catch(e){document.getElementById('error').textContent=e.message}}form.onsubmit=e=>{e.preventDefault();open(form.querySelector('input').value)};${locked?'':"open('');"}</script></html>`}
