const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{fs.mkdirSync('checks/v6',{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4318');
async function settings(){await p.getByRole('button',{name:'个性化设置',exact:true}).click()}
async function done(){await p.locator('#settings .dialog-done button').click();await p.waitForTimeout(350)}
async function theme(id){await settings();await p.locator('[data-settings-tab=themes]').click();await p.locator(`[data-v2-theme=${id}]`).click();await done()}
await settings();await p.locator('[data-settings-tab=copy]').click();assert.equal(await p.locator('[data-copy-theme]').count(),7);await p.locator('[data-copy-theme=base]').click();assert(await p.locator('#copy-title').evaluate(e=>e.readOnly));await p.locator('[data-copy-mode=custom]').click();await p.locator('#copy-title').fill('我的世界\n从这里开始');await p.locator('#copy-intro').fill('收藏今天\n遇见明天');await p.screenshot({path:'checks/v6/copy.png'});await done();await theme('base');assert.equal(await p.locator('.base-composition h1').innerText(),'我的世界\n从这里开始');await p.reload();assert.equal(await p.locator('.base-composition h1').innerText(),'我的世界\n从这里开始');await settings();await p.locator('[data-settings-tab=copy]').click();await p.locator('#copy-title').fill('字'.repeat(40));assert.equal((await p.locator('#copy-title').inputValue()).length,24);await p.locator('#copy-intro').fill('一\n二\n三\n四');assert.equal(await p.locator('#copy-intro').inputValue(),'一\n二\n三');await p.locator('[data-copy-mode=default]').click();assert.equal(await p.locator('#copy-title').inputValue(),'你的互联网，自成一隅。');await done();
for(const id of ['paper','cinema','cosmos','flip','music','rain']){await theme(id);await p.screenshot({path:`checks/v6/${id}.png`});}
await theme('paper');const paper=await p.locator('.newspaper').boundingBox();assert(paper.width>1250);assert.equal(await p.locator('.paper-more article').count(),3);
await theme('cinema');await p.locator('.dock-trigger').hover();await p.waitForTimeout(350);assert.equal(await p.locator('.space-film-copy b').count(),3);await p.screenshot({path:'checks/v6/poster-dock.png'});
await theme('cosmos');await p.waitForTimeout(400);const el=p.locator('.is-center .planet-surface'),before=await el.evaluate(e=>parseFloat(e.style.getPropertyValue('--longitude'))),c=await el.boundingBox();await p.mouse.move(c.x+c.width/2,c.y+c.height/2);await p.mouse.down();await p.mouse.move(c.x+c.width/2+140,c.y+c.height/2+40,{steps:12});const after=await el.evaluate(e=>parseFloat(e.style.getPropertyValue('--longitude')));assert(after-before>90);await p.mouse.up();assert.equal(await el.evaluate(e=>getComputedStyle(e).transform),'none');
await p.setViewportSize({width:390,height:844});await theme('paper');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'checks/v6/mobile-paper.png',fullPage:true});await settings();await p.locator('[data-settings-tab=copy]').click();await p.screenshot({path:'checks/v6/mobile-copy.png'});assert.deepEqual(errors,[]);await b.close();console.log('PASS: per-theme copy, immediate edits/reload, limits/defaults, seven themes, full-width newspaper, film dock, axial drag, mobile and no page errors');})().catch(e=>{console.error(e);process.exit(1)});
