const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{fs.mkdirSync('checks/v4',{recursive:true});const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4318');await p.waitForSelector('.home');assert.equal(await p.locator('.header-right button').count(),2);async function theme(id){await p.getByRole('button',{name:'个性化设置',exact:true}).click();await p.locator('[data-settings-tab=themes]').click();await p.locator(`[data-v2-theme=${id}]`).click();await p.locator('#settings .dialog-done button').click()}
await theme('music');await p.getByRole('button',{name:'播放音乐',exact:true}).click();await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>audioCtx.state),'running');assert.equal(await p.locator('.equalizer i').first().evaluate(x=>getComputedStyle(x).animationPlayState),'running');await p.getByRole('button',{name:'暂停音乐',exact:true}).click();assert.equal(await p.evaluate(()=>audioCtx.state),'suspended');assert.equal(await p.locator('.vinyl').evaluate(x=>getComputedStyle(x).animationPlayState),'paused');const progress=await p.locator('#music-progress').getAttribute('style');await p.waitForTimeout(1500);assert.equal(await p.locator('#music-progress').getAttribute('style'),progress);await p.locator('.player-controls .select-trigger').click();await p.getByRole('option',{name:'微光 · 专注'}).click();assert.equal(await p.evaluate(()=>trackIndex),1);await p.getByRole('button',{name:'静音',exact:true}).click();assert.equal(await p.locator('.mute-control').innerText(),'');await p.screenshot({path:'checks/v4/music.png'});
await p.getByRole('button',{name:'个性化设置',exact:true}).click();await p.locator('[data-pref=mode][data-value=light]').click();await p.locator('[data-pref=color][data-value="#467ea5"]').click();const color=await p.locator('body').evaluate(x=>getComputedStyle(x).backgroundColor);await p.locator('[data-pref=color][data-value="#a95e76"]').click();assert.notEqual(await p.locator('body').evaluate(x=>getComputedStyle(x).backgroundColor),color);await p.screenshot({path:'checks/v4/settings.png'});await p.locator('[data-settings-tab=type]').click();assert.equal(await p.locator('.font-specimen').count(),1);await p.locator('[data-settings-tab=layout]').click();assert.equal(await p.locator('.width-specimen').count(),1);await p.locator('#settings .dialog-done button').click();
await theme('cinema');for(const id of ['sea','night','road']){await p.locator(`button[data-poster=${id}]`).click();await p.locator('.poster-photo').evaluate(el=>el.decode());await p.screenshot({path:`checks/v4/cinema-${id}.png`});}await p.locator('.dock-trigger').hover();assert.equal(await p.locator('.space-film').count(),3);await p.screenshot({path:'checks/v4/cinema-dock.png'});
await theme('cosmos');await p.mouse.move(700,100);await p.waitForTimeout(200);const c=await p.locator('.orbit-body.is-center').boundingBox();await p.mouse.move(c.x+c.width/2,c.y+c.height/2);await p.mouse.down();await p.mouse.move(c.x+c.width/2+190,c.y+c.height/2+65,{steps:12});assert(Math.abs(await p.evaluate(()=>orbitTurn))>1);await p.mouse.up();await p.waitForTimeout(4000);assert(Math.abs(await p.evaluate(()=>orbitTurn))<.1);assert.equal(await p.locator('.orbit-hint').count(),0);await p.screenshot({path:'checks/v4/cosmos.png'});
await theme('flip');assert.equal(await p.locator('#clock-seconds').count(),1);await p.getByRole('button',{name:'专注模式',exact:true}).click();assert.equal(await p.getByRole('button',{name:'重置',exact:true}).count(),0);await p.getByRole('button',{name:'开始专注',exact:true}).click();assert.equal(await p.getByRole('button',{name:'重置',exact:true}).count(),1);await p.getByRole('button',{name:'重置',exact:true}).click();assert.equal(await p.getByRole('button',{name:'重置',exact:true}).count(),0);await p.getByRole('button',{name:'当前时间',exact:true}).click();await p.screenshot({path:'checks/v4/flip.png'});
await theme('paper');assert((await p.locator('.paper-meta').innerText()).includes('期'));await p.screenshot({path:'checks/v4/paper.png'});await theme('rain');await p.waitForTimeout(1300);assert.equal(await p.locator('.rain-calendar').count(),1);await p.screenshot({path:'checks/v4/rain.png'});
await p.setViewportSize({width:390,height:844});for(const id of ['music','cinema','paper','flip','cosmos','rain']){await theme(id);await p.waitForTimeout(300);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+' overflow');await p.screenshot({path:`checks/v4/mobile-${id}.png`,fullPage:true})}assert.deepEqual(errors,[]);console.log('PASS: header, tabs, palette, dialog completion, audio linked state, custom selector, 3 posters, themed dock, orbit drag recovery, focus states, seconds, issue, mobile');await b.close()})().catch(e=>{console.error(e);process.exit(1)});

