const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{fs.mkdirSync('checks/v2',{recursive:true});const b=await chromium.launch({channel:'msedge',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4318');await p.waitForSelector('.home-base');assert.equal(await p.locator('header nav').count(),0);await p.screenshot({path:'checks/v2/base.png'});
await p.getByRole('button',{name:'主题风格设置'}).click();assert.equal(await p.locator('[data-v2-theme]').count(),7);await p.screenshot({path:'checks/v2/themes.png'});
for(const theme of ['paper','music','cinema','cosmos','flip','rain']){await p.locator(`[data-v2-theme=${theme}]`).click();await p.getByRole('button',{name:'关闭外观设置'}).click();await p.waitForSelector('.home-'+theme);await p.screenshot({path:`checks/v2/${theme}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),theme+' desktop overflow');await p.getByRole('button',{name:'主题风格设置'}).click()}
await p.locator('[data-v2-theme=music]').click();await p.getByRole('button',{name:'浅色',exact:true}).click();await p.getByRole('button',{name:'湖蓝',exact:true}).click();await p.getByRole('button',{name:'关闭外观设置'}).click();assert.equal(await p.locator('body').getAttribute('data-dark'),'false');assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent')),'#467ea5');await p.screenshot({path:'checks/v2/music-light-blue.png'});
await p.getByRole('button',{name:'暂停唱片动效'}).click();assert.equal(await p.locator('.vinyl.spinning').count(),0);await p.getByRole('button',{name:'播放唱片动效'}).click();assert.equal(await p.locator('.vinyl.spinning').count(),1);
await p.mouse.move(600,600);await p.mouse.wheel(0,220);await p.waitForSelector('.workspace');assert.equal(await p.locator('body').getAttribute('data-theme'),'music');await p.waitForTimeout(950);await p.mouse.wheel(0,-200);await p.waitForTimeout(100);assert.equal(await p.locator('.workspace').count(),1);await p.waitForTimeout(450);await p.mouse.wheel(0,-200);await p.waitForSelector('.home-music');await p.waitForTimeout(950);
await p.getByRole('button',{name:'打开搜索',exact:true}).click();await p.locator('[data-search=saved]').click();await p.locator('#search-input').fill('Notion');await p.locator('.result').waitFor();await p.getByRole('button',{name:'关闭搜索',exact:true}).click();
await p.locator('[data-v2=enter]').click();await p.waitForSelector('.workspace');await p.getByRole('button',{name:'场景外观'}).click();await p.locator('[data-v2-theme=paper]').click();await p.getByRole('button',{name:'关闭外观设置'}).click();assert.equal(await p.locator('body').getAttribute('data-theme'),'paper');await p.screenshot({path:'checks/v2/paper-space.png'});await p.waitForTimeout(950);await p.locator('[data-v2=return]').click();assert.equal(await p.locator('body').getAttribute('data-theme'),'music');
await p.getByRole('button',{name:'主题风格设置'}).click();await p.locator('[data-v2-theme=flip]').click();await p.getByRole('button',{name:'关闭外观设置'}).click();await p.getByRole('button',{name:'专注模式',exact:true}).click();assert.equal(await p.locator('.digit-value').allTextContents().then(x=>x.join('')),'2500');await p.getByRole('button',{name:'开始专注',exact:true}).click();await p.waitForTimeout(2300);assert.notEqual(await p.locator('.digit-value').allTextContents().then(x=>x.join('')),'2500');await p.getByRole('button',{name:'暂停专注',exact:true}).click();
await p.setViewportSize({width:390,height:844});for(const theme of ['base','paper','music','cinema','cosmos','flip','rain']){await p.getByRole('button',{name:'主题风格设置'}).click();await p.locator(`[data-v2-theme=${theme}]`).click();await p.getByRole('button',{name:'关闭外观设置'}).click();await p.screenshot({path:`checks/v2/mobile-${theme}.png`,fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),theme+' mobile overflow')}
await p.reload();assert.equal(await p.locator('body').getAttribute('data-theme'),'rain');assert.deepEqual(errors,[]);console.log('PASS: seven themes, theme picker, color/mode, music controls, guarded wheel navigation, search, scene override, focus timer, persistence, mobile overflow, no runtime errors');await b.close()})().catch(e=>{console.error(e);process.exit(1)});

