const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),fixture=require('./baseline.json');
const checks=[],errors=[];let browser;
const tick=p=>p.waitForTimeout(400);
async function atMode(p,mode){await p.locator('[data-at-mode="'+mode+'"]').click();await tick(p)}
async function layout(p,id){await p.locator('[data-at=layouts]').click();await p.locator('[data-at-layout='+id+']').click();await p.mouse.move(20,550);await tick(p)}
async function hover(p,selector){await p.locator(selector).hover({force:true});await p.waitForTimeout(80)}
async function nodeClick(p,key){const q='.at-node-main[data-at-focus="'+key+'"]';await hover(p,q);await p.locator(q).click();await tick(p)}
const positions=p=>p.locator('.at-node[data-level="1"]').evaluateAll(es=>Object.fromEntries(es.map(e=>{const r=e.getBoundingClientRect();return[e.dataset.key,{x:r.x+r.width/2,y:r.y+Math.min(20,r.height/2),kind:e.dataset.kind}]})));
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});const c=await browser.newContext({viewport:{width:1573,height:1041}});
 await c.addInitScript(value=>{localStorage.setItem('yiyu-prototype-v1',JSON.stringify({...value,signed:true,prefs:{...value.prefs,mode:'dark',width:'wide',membership:{expiresAt:Date.now()+86400000}}}));localStorage.removeItem('shiyu-space-atlas-v1')},fixture);
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4318');await p.evaluate(()=>goSpace('create'));await tick(p);
 const dataBefore=await p.evaluate(()=>JSON.stringify(data));
 await p.locator('.workspace .global-search-trigger').click();await p.locator('.workspace .global-search-field input').fill('Notion');assert.match(await p.locator('.workspace .global-search-results').innerText(),/Notion/);assert.match(await p.locator('.workspace .global-search-results').innerText(),/工作空间/);await p.locator('.workspace .global-search-field input').press('Escape');
 await p.locator('.workspace .space-mode-entry').hover();await p.locator('[data-space-mode=atlas]').click();await tick(p);
 assert.equal(await p.locator('.at-search').count(),0);await p.locator('#space-atlas .global-search-trigger').click();await p.locator('#space-atlas .global-search-field input').fill('Notion');assert.match(await p.locator('#space-atlas .global-search-results').innerText(),/工作空间/);await p.locator('#space-atlas .global-search-field input').press('Escape');checks.push('One shared global URL search in daily and atlas modes, including other spaces');
 await atMode(p,'3d');await layout(p,'solar');assert.equal(await p.locator('.at-shell').getAttribute('data-presentation'),'solar');assert((await p.locator('.at-orbit-track').count())>=3);
 const tracks=await p.locator('.at-orbit-track').evaluateAll(es=>es.map(e=>({id:+e.dataset.orbit,capacity:+e.dataset.capacity,speed:+e.dataset.speed})).sort((a,b)=>a.id-b.id));assert(tracks.every((t,i)=>!i||t.speed<tracks[i-1].speed));const occupancy=await p.locator('.at-node[data-orbit]').evaluateAll(es=>es.reduce((m,e)=>(m[e.dataset.orbit]=(m[e.dataset.orbit]||0)+1,m),{}));for(const [i,n]of Object.entries(occupancy))assert(n<=tracks[i].capacity);assert(Math.max(...Object.values(occupancy))-Math.min(...Object.values(occupancy))<=1);
 const a=await positions(p);await p.waitForTimeout(900);const b=await positions(p);assert(distance(a['c:ai'],b['c:ai'])>5);
 await hover(p,'.at-node-main[data-at-focus="c:ai"]');const frozen=await positions(p);await p.waitForTimeout(250);assert(distance(frozen['c:ai'],(await positions(p))['c:ai'])<.2);
 assert.equal(await p.locator('.at-packet circle:not(.at-packet-head)').count(),0);assert.equal(await p.locator('.at-packet-head').first().getAttribute('r'),'1.65');assert((await p.locator('.at-packet[data-phase=incoming]').count())===1);
 assert(await p.locator('.at-line.is-upstream').first().evaluate(e=>getComputedStyle(e).strokeDasharray!=='none'));await p.waitForTimeout(500);assert((await p.locator('.at-packet[data-phase=outgoing]').count())>=1);checks.push('Independent balanced orbital tracks; inner rings faster; hover pauses planets; thin inbound then outbound current remains on dashed/solid edges');
 await p.mouse.move(20,550);await p.locator('[data-at=motion]').click();await tick(p);await p.screenshot({path:'checks/space-atlas/v5-solar-dark.png'});
 assert.equal(await p.locator('.at-node[data-kind=add] .at-node-menu').count(),0);assert.equal(await p.locator('.at-node[data-kind=add]').count(),1);
 await nodeClick(p,'c:mock-inspiration-v1-0');assert.match(await p.locator('.at-summary').innerText(),/150/);assert.equal(await p.locator('.at-node[data-kind=group][data-level="1"]').count(),5);
 const parentBefore=await p.locator('.at-node.is-parent').boundingBox();const beforeDepth=await p.locator('.at-node[data-level="1"]').evaluateAll(es=>es.map(e=>e.dataset.depth));
 await p.mouse.move(60,400);await p.mouse.down();await p.mouse.move(220,430,{steps:8});await p.mouse.up();await tick(p);assert.notDeepEqual(await p.locator('.at-node[data-level="1"]').evaluateAll(es=>es.map(e=>e.dataset.depth)),beforeDepth);const parentAfter=await p.locator('.at-node.is-parent').boundingBox();assert(Math.abs(parentBefore.x-parentAfter.x)<1);await p.locator('[data-at=fit]').click();await tick(p);
 await p.screenshot({path:'checks/space-atlas/v5-solar-scene.png'});checks.push('True 3D orbit projection rotates with the camera; labels face the reader and upstream parent stays in place');
 await nodeClick(p,'b:g:mock-inspiration-v1-0-g0:link');assert.equal(await p.locator('.at-node[data-level="0"]').getAttribute('data-key'),'g:mock-inspiration-v1-0-g0');assert.equal(await p.locator('.at-node[data-kind=link][data-level="1"]').count(),9);await nodeClick(p,'b:g:mock-inspiration-v1-0-g0:link');assert((await p.locator('.at-node[data-kind=link][data-level="1"]').count())>9);await p.locator('[data-at=back]').click();await tick(p);
 const pos=await positions(p),keys=Object.keys(pos).filter(k=>pos[k].kind==='group');const first=keys[0],last=keys.at(-1),order=await p.evaluate(()=>space().scenes.find(x=>x.id==='mock-inspiration-v1-0').groups.map(g=>g.id));
 await p.mouse.move(pos[first].x,pos[first].y);await p.mouse.down();await p.mouse.move(pos[last].x,pos[last].y,{steps:14});await p.waitForTimeout(90);assert.equal(await p.locator('.is-sort-target').getAttribute('data-key'),last);await p.mouse.up();await p.mouse.move(20,550);await p.waitForTimeout(1300);const sorted=await p.evaluate(()=>space().scenes.find(x=>x.id==='mock-inspiration-v1-0').groups.map(g=>g.id));assert.equal(sorted.at(-1),order[0]);checks.push('Drag across orbital slots persists sibling order, keeping parent relationships unchanged');
 const menu=p.locator('.at-node[data-level="0"] .at-node-menu');await menu.click({force:true});assert.equal(await p.locator('[data-at-manage=up],[data-at-manage=down]').count(),0);await p.locator('.at-drawer-done').click();assert(await p.locator('.at-drawer').isHidden());
 await p.locator('[data-at-create]').click();const editor=p.locator('#organization-name,.at-existing-editor input').first();await editor.fill('轨道新增测试');await editor.press('Enter');await tick(p);assert(await p.evaluate(()=>space().scenes.find(x=>x.id==='mock-inspiration-v1-0').groups.some(g=>g.name==='轨道新增测试')));assert.equal(await p.locator('.at-node[data-kind=add]').count(),1);checks.push('Dashed plus node creates through existing editor, remains last, and management has Done without up/down controls');
 for(const id of ['radial','organization','mindmap']){await atMode(p,'2d');await layout(p,id);assert(await p.locator('[data-at-create]').count());assert.equal(await p.locator('.at-site-view').count(),0)}
 await layout(p,'radial');await p.locator('[data-at=back]').click();await tick(p);await p.screenshot({path:'checks/space-atlas/v5-radial.png'});
 await p.evaluate(()=>{scope='global';settingsTab='space-entry';renderSettings();show('#settings')});await tick(p);assert.equal(await p.locator('[data-entry-policy]').count(),fixture.data.length);await p.screenshot({path:'checks/space-atlas/v5-entry-settings.png'});
 await p.locator('[data-entry-policy="work"]').selectOption('fixed',{force:true});await p.locator('[data-entry-fixed="work"]').selectOption('3d:solar',{force:true});await p.locator('#settings .dialog-heading [data-action=close]').click();await p.evaluate(()=>goSpace('work'));await tick(p);assert.equal(await p.locator('.at-shell').getAttribute('data-presentation'),'solar');
 await atMode(p,'2d');await layout(p,'mindmap');await p.evaluate(()=>goSpace('life'));await p.evaluate(()=>goSpace('work'));await tick(p);assert.equal(await p.locator('.at-shell').getAttribute('data-presentation'),'solar');checks.push('Global per-space fixed opening style survives switching away; last-choice policy remains separate');
 await p.evaluate(()=>{scope='global';settingsTab='space-entry';renderSettings();show('#settings')});await p.locator('[data-entry-policy="work"]').selectOption('last',{force:true});await p.locator('#settings .dialog-heading [data-action=close]').click();await atMode(p,'2d');await layout(p,'organization');await p.evaluate(()=>goSpace('life'));await p.evaluate(()=>goSpace('work'));await tick(p);assert.equal(await p.locator('.at-shell').getAttribute('data-layout'),'organization');assert.equal(await p.locator('.at-shell').getAttribute('data-mode'),'2d');checks.push('Last-choice mode restores the per-space layout independently');
 for(const [width,height]of [[390,844],[1280,847],[2560,1440]]){await p.setViewportSize({width,height});await atMode(p,'3d');await layout(p,'solar');await p.locator('[data-at=motion]').click();await tick(p);const clear=await p.evaluate(()=>{const r=document.querySelector('.at-header-actions').getBoundingClientRect();return [...document.querySelectorAll('.mode-pull-cord,.color-pull-cord')].every(e=>{const b=e.getBoundingClientRect();return Math.min(r.right,b.right)<=Math.max(r.left,b.left)||Math.min(r.bottom,b.bottom)<=Math.max(r.top,b.top)})});assert(clear,'cord/header clear at '+width);await p.screenshot({path:'checks/space-atlas/v5-solar-'+width+'.png'})}
 await p.setViewportSize({width:1573,height:1041});await p.evaluate(()=>{prefs.mode='light';render()});await tick(p);await p.screenshot({path:'checks/space-atlas/v5-solar-light.png'});
 const filePage=await c.newPage();filePage.on('pageerror',e=>errors.push(e.message));await filePage.goto(pathToFileURL(path.resolve('dist/index.html')).href);await filePage.evaluate(()=>goSpace('work'));await filePage.locator('.workspace .space-mode-entry').hover();await filePage.locator('[data-space-mode=atlas]').click();await atMode(filePage,'3d');await layout(filePage,'solar');assert(await filePage.locator('.at-orbit-track').count());checks.push('Light/dark and 390/1280/2560 viewports verified; direct file preview loads');
 assert.deepEqual(errors,[]);fs.writeFileSync('checks/space-atlas/v5-report.json',JSON.stringify({checks,errors,status:'PASS'},null,2));console.log(JSON.stringify({checks,errors,status:'PASS'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close()});
