const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {pathToFileURL}=require('node:url');const fixture=require('./baseline.json');
const report=[],errors=[];const wait=p=>p.waitForTimeout(400);
async function mode(p,id){await p.locator(id==='atlas'?'.workspace .space-mode-entry':'#space-atlas .space-mode-entry').hover();await p.locator('[data-space-mode='+id+']').click();await wait(p)}
const positions=p=>p.locator('.at-node').evaluateAll(es=>Object.fromEntries(es.map(e=>{const r=e.getBoundingClientRect();return[e.dataset.key,{x:r.x+r.width/2,y:r.y+r.height/2}]})));
const delta=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
async function cordsClear(p){return p.evaluate(()=>{const buttons=document.querySelector('#space-atlas[open] .at-header-actions')||document.querySelector('.workspace .space-top-actions'),a=buttons.getBoundingClientRect();return [...document.querySelectorAll('.mode-pull-cord,.color-pull-cord')].every(e=>{const b=e.getBoundingClientRect();return Math.min(a.right,b.right)<=Math.max(a.left,b.left)||Math.min(a.bottom,b.bottom)<=Math.max(a.top,b.top)})})}
async function cordsHidden(p){assert(await p.locator('.mode-pull-cord').evaluate(e=>getComputedStyle(e).visibility==='hidden'));assert(await p.locator('.color-pull-cord').evaluate(e=>getComputedStyle(e).visibility==='hidden'))}
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1573,height:1041}});
 await context.addInitScript(value=>{localStorage.setItem('yiyu-prototype-v1',JSON.stringify({...value,signed:true,prefs:{...value.prefs,membership:{expiresAt:Date.now()+86400000}}}));localStorage.removeItem('shiyu-space-atlas-v1')},fixture);
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4318');await p.evaluate(()=>{prefs.width='wide';goSpace('create')});await wait(p);
 assert(await cordsClear(p));const original=await p.evaluate(()=>JSON.stringify(data));await mode(p,'atlas');assert(await cordsClear(p));
 assert.equal(await p.locator('.at-context,.at-path,.at-peers').count(),0);assert.match(await p.locator('[data-at=layouts]').innerText(),/径向环绕/);
 await p.locator('[data-at=layouts]').click();await cordsHidden(p);assert.deepEqual(await p.locator('.at-layout-menu b').allTextContents(),['径向环绕','层级结构','思维脉络']);await p.locator('[data-at-layout=radial]').click();await wait(p);
 const target=p.locator('.at-node[data-key="c:mock-inspiration-v1-0"] .at-node-main');await p.mouse.move(20,400);await target.hover();await p.waitForTimeout(210);
 const phases=()=>p.locator('.at-packet').evaluateAll(es=>({incoming:es.filter(e=>e.dataset.phase==='incoming').length,outgoing:es.filter(e=>e.dataset.phase==='outgoing').length}));
 assert.deepEqual(await phases(),{incoming:1,outgoing:0});await p.screenshot({path:'checks/space-atlas/v4-incoming.png'});await p.waitForTimeout(650);
 assert.deepEqual(await phases(),{incoming:0,outgoing:5});await p.screenshot({path:'checks/space-atlas/v4-outgoing.png'});assert.equal(await p.locator('.at-flow').count(),0);report.push('One incoming packet arrives before five child packets depart simultaneously');
 await p.mouse.move(20,400);await wait(p);const before=await positions(p),source=before['c:ai'];
 await p.mouse.move(source.x,source.y-15);await p.mouse.down();await p.mouse.move(source.x+55,source.y+20,{steps:6});await p.waitForTimeout(90);
 const mild=await positions(p);assert(delta(mild['c:ai'],before['c:ai'])>50);assert(delta(mild['g:assistants'],before['g:assistants'])>50);assert(delta(mild['c:mock-inspiration-v1-0'],before['c:mock-inspiration-v1-0'])<.1);
 const obstacle=before['c:mock-inspiration-v1-0'];await p.mouse.move(obstacle.x,obstacle.y,{steps:1});await p.waitForTimeout(100);const pushed=await positions(p);assert(delta(pushed['c:mock-inspiration-v1-0'],before['c:mock-inspiration-v1-0'])>10);await p.screenshot({path:'checks/space-atlas/v4-drag.png'});
 await p.mouse.up();await p.mouse.move(20,400);await p.waitForTimeout(1300);const settled=await positions(p);for(const key in before)assert(delta(settled[key],before[key])<.5,'settled '+key);assert.equal(await p.locator('.at-node[data-level="0"]').getAttribute('data-key'),'s:create');assert.equal(await p.evaluate(()=>JSON.stringify(data)),original);report.push('Branch moves together; untouched branch stays still; collision pushes; release restores every node without changing data or focus');
 await p.locator('.at-node-main[data-at-focus="c:mock-inspiration-v1-0"]').click();await wait(p);const groupKey='g:mock-inspiration-v1-0-g0';await p.locator('.at-node-main[data-at-focus="b:'+groupKey+':link"]').click();await wait(p);
 const circle=await p.locator('.at-node').evaluateAll(es=>{const centre=es.find(e=>e.dataset.level==='0').getBoundingClientRect(),cx=centre.x+centre.width/2,cy=centre.y+centre.height/2;return es.filter(e=>e.dataset.level==='1').map(e=>{const r=e.getBoundingClientRect();return Math.round(Math.hypot(r.x+r.width/2-cx,r.y+r.height/2-cy))})});assert(new Set(circle).size<=2,'regular concentric rings');
 const pp=await positions(p);assert(pp['c:mock-inspiration-v1-0'].y<pp[groupKey].y);const parBefore=pp['c:mock-inspiration-v1-0'];await p.screenshot({path:'checks/space-atlas/v4-rings.png'});
 await p.locator('[data-at-mode="3d"]').click();await wait(p);const parent3d=(await positions(p))['c:mock-inspiration-v1-0'];await p.mouse.move(60,500);await p.mouse.down();await p.mouse.move(850,560,{steps:20});await p.mouse.up();await wait(p);assert(delta((await positions(p))['c:mock-inspiration-v1-0'],parent3d)<.1,'parent stays at fixed top-left position while rotating');report.push('Focused children form two exact rings; parent remains fixed above-left in 3D');
 await p.locator('[data-at=fit]').click();await wait(p);const link=p.locator('.at-node[data-kind=link] a').first();assert.equal(await link.getAttribute('target'),'_blank');const popupPromise=context.waitForEvent('page');await link.click();const popup=await popupPromise;await popup.close();assert.equal(await p.locator('.at-node[data-level="0"]').getAttribute('data-key'),groupKey);
 // Dragging a link must not open it, whereas a normal click above still does.
 let unexpected=0;const listener=()=>unexpected++;context.on('page',listener);const lr=await link.boundingBox();await p.mouse.move(lr.x+lr.width/2,lr.y+lr.height/2);await p.mouse.down();await p.mouse.move(lr.x+lr.width/2+50,lr.y+lr.height/2+30,{steps:5});await p.mouse.up();await p.waitForTimeout(1200);assert.equal(unexpected,0);context.off('page',listener);report.push('Click opens URL directly; dragging a URL does not navigate');
 await p.locator('[data-at-header=share]').click();await cordsHidden(p);assert(await p.locator('#space-share-dialog').isVisible());await p.locator('#space-share-dialog').evaluate(e=>e.close());await wait(p);assert(await p.locator('.mode-pull-cord').isVisible());
 await p.locator('.at-node[data-level="0"]').hover();await p.locator('.at-node[data-level="0"] [data-at-details]').click();await cordsHidden(p);await p.locator('[data-at=close-drawer]').click();await wait(p);assert(await p.locator('.mode-pull-cord').isVisible());report.push('Cords disappear for dialogs and graph management panels, then return');
 for(const size of [{width:1280,height:800},{width:390,height:844},{width:2560,height:1440}]){await p.setViewportSize(size);await wait(p);assert(await cordsClear(p),'graph cord clearance '+size.width);await mode(p,'daily');assert(await cordsClear(p),'daily cord clearance '+size.width);await mode(p,'atlas');}
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{prefs.mode='dark';goSpace('life')});await wait(p);await p.screenshot({path:'checks/space-atlas/v4-mobile.png'});report.push('Wide layout at 390/1280/2560: cords and actions do not overlap in either mode');
 await context.close();const file=await browser.newPage();file.on('pageerror',e=>errors.push(e.message));await file.goto(pathToFileURL(path.resolve('dist/index.html')).href);await file.evaluate(()=>goSpace('life'));await mode(file,'atlas');assert.equal(await file.locator('.at-context').count(),0);await file.close();report.push('Direct file preview');
 fs.writeFileSync('checks/space-atlas/v4-report.json',JSON.stringify({report,errors},null,2));console.log(JSON.stringify({report,errors},null,2));assert.deepEqual(errors,[]);await browser.close();console.log('PASS');
})().catch(e=>{console.error(e);process.exit(1)});
