const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {view,save}=require('../admin-config.cjs');
test('payment configuration persists switches, keeps one channel, and never echoes secrets',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiyu-payment-config-'));try{const file=path.join(dir,'config.json');save('wechat',{values:{appId:'wx1111111111111111',apiV3Key:'0123456789abcdef0123456789abcdef'}},file);assert.equal(view(file).items[0].configured.apiV3Key,true);assert(!JSON.stringify(view(file)).includes('0123456789abcdef'));save('wechat',{values:{apiV3Key:''}},file);assert.equal(view(file).items[0].configured.apiV3Key,true);save('alipay',{enabled:false},file);assert.throws(()=>save('wechat',{enabled:false},file),/至少保留/);assert.equal(view(file).items[0].enabled,true);assert.equal(view(file).items[1].enabled,false);assert.throws(()=>save('wechat',{values:{apiV3Key:'short'}},file));assert.throws(()=>save('wechat',{values:{privateKey:'not a key'}},file));assert.throws(()=>save('wechat',{values:{privateKeyPath:'/tmp/secret'}},file));}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('disabled channel cannot create positive orders but existing orders remain queryable',async t=>{
 const {PaymentService}=require('../service.cjs'),{PaymentStore}=require('../store.cjs');const store=new PaymentStore(':memory:');t.after(()=>store.close());
 const plan={id:'monthly',name:'月会员',price:10,days:30,enabled:true};let queried=false;
 const order=store.create({userId:'u',provider:'wechat',requestId:'existing',plan,amount:1000});store.checked(order.id);
 const service=new PaymentService({config:{wechat:{enabled:false}},providers:{wechat:{query:async()=>{queried=true}}},store,getPlans:async()=>[plan]});
 await assert.rejects(()=>service.create({id:'u'},{provider:'wechat',planId:'monthly',quantity:2,requestId:'1234567890123456',accepted:true}),e=>e.code==='PROVIDER_DISABLED');
 assert(service.provider('wechat'));const result=await service.query({id:'u'},order.id);assert.equal(result.id,order.id);assert.equal(queried,false);
});
