'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),vm=require('node:vm');
const {once}=require('node:events'),{pathToFileURL}=require('node:url');
const ts=require('../../../聚合管理后台/node_modules/typescript');
const {createMembershipService}=require('../membership.cjs');
test('actual user middleware: admin mutations, public privacy, session identity, quota and read-only GET routes',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiyu-middleware-'));
  const plans=[{id:'free',name:'免费版',entitlements:['space-limit','scene-limit','group-limit'].map(key=>({key,enabled:true,value:1}))},{id:'monthly',name:'月度会员',version:1,entitlements:[{key:'themes',kind:'selection',enabled:true,value:['test-theme']}]}];
  const memberships=createMembershipService({usersFile:path.join(dir,'users.json'),invitationsFile:path.join(dir,'invitations.json'),readPlans:()=>plans,readExperience:()=>({enabled:false,values:{}})});
  memberships.writeUsers([{id:'u',name:'测试',phone:'13800138000',password:'test-password',member:false,memberEvents:[],accountData:[],blacklisted:false}]);
  const adminRoot=path.resolve(__dirname,'../../../聚合管理后台');
  const code=ts.transpileModule(fs.readFileSync(path.join(adminRoot,'shiyu-user-plugin.ts'),'utf8').replaceAll('import.meta.url',JSON.stringify(pathToFileURL(path.join(dir,'entry.ts')).href)),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  const fakeSession={session:req=>req.headers['x-test-user']==='u'?'u':null,issueSession:()=> 'test-token',logout:()=>{}};
  const runtimeRequire=name=>{
    if(name.includes('experience-test/store'))return {get:()=>({enabled:false,values:{}})};
    if(name.includes('theme-access/store'))return fakeSession;
    if(name.includes('payments/membership'))return {createMembershipService:()=>memberships};
    if(name.includes('payments/tool-quotas'))return require('../tool-quotas.cjs');
    if(name==='node:module')return {createRequire:()=>runtimeRequire};
    if(name==='./platform-access-plugin')return {getPlatformSession:req=>req.headers.authorization==='admin'?{superadmin:true,admin:{name:'测试管理员'},applicationIds:['shiyu']}:null};
    if(name==='./shiyu-invitation-plugin')return {invitationCodeFor:()=>undefined,invitationForCode:()=>undefined,settleInvitations:()=>memberships.settleInvitations()};
    if(name==='./shiyu-library')return {};
    // Pure dependencies introduced by the current admin middleware; no external IO.
    if(name==='./shiyu-onboarding'||name==='./analytics/runtime')return require(path.join(adminRoot,name+'.ts'));
    if(name.startsWith('node:'))return require(name);
    throw Error('Unexpected dependency; external services forbidden: '+name);
  };
  const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:runtimeRequire,process:{env:{SHIYU_USERS_FILE:path.join(dir,'users.json')}},URL,Date,Error,console,Buffer,structuredClone,fetch:()=>{throw Error('External fetch forbidden')}});
  let middleware;module.exports.shiyuUserPlugin().configureServer({middlewares:{use:fn=>{middleware=fn}}});
  const server=http.createServer((req,res)=>{Promise.resolve(middleware(req,res,()=>{res.writeHead(404);res.end()})).catch(error=>{res.writeHead(500);res.end(error.message)})});server.listen(0,'127.0.0.1');await once(server,'listening');
  t.after(()=>{server.close();server.closeAllConnections();fs.rmSync(dir,{recursive:true,force:true})});
  const base='http://127.0.0.1:'+server.address().port;
  const request=async(url,method='GET',body,admin=false)=>{const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json','x-test-user':'u',...(admin?{Authorization:'admin'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}};
  assert.equal((await request('/api/shiyu/users')).status,403);
  let result=await request('/api/shiyu/users/u','PUT',{action:'member',permanent:true,planId:'monthly'},true);assert.equal(result.status,200);assert.equal(result.data.user.membership.permanent,true);
  assert.equal(result.data.user.memberEvents[0].operator,'测试管理员');
  const publicBefore=fs.readFileSync(path.join(dir,'users.json'),'utf8');
  result=await request('/api/shiyu/auth/session');assert.equal(result.data.user.member,true);assert.equal(result.data.user.entitlements[0].value[0],'test-theme');
  result=await request('/api/shiyu/auth/membership-records');assert.deepEqual(result.data.items,[]);
  await request('/api/shiyu/auth/invitations');assert.equal(fs.readFileSync(path.join(dir,'users.json'),'utf8'),publicBefore);
  result=await request('/api/shiyu/auth/login','POST',{account:'13800138000',credential:'test-password',mode:'password'});assert.equal(result.status,200);assert.equal(result.data.user.memberEvents,undefined);assert.equal(result.data.user.password,undefined);
  result=await request('/api/shiyu/users/u','PUT',{action:'cancel-member'},true);assert.equal(result.status,200);
  result=await request('/api/shiyu/auth/session');assert.equal(result.data.user.member,false);assert.equal(result.data.user.planId,'free');
  result=await request('/api/shiyu/users','GET',undefined,true);assert.equal(result.data.items[0].memberEvents.length,2);
  const space=id=>({id,scenes:[{id:'s',groups:[]}]});
  result=await request('/api/shiyu/auth/account','PUT',{userId:'u',data:[space('a'),space('b')]});assert.equal(result.status,400);assert.match(result.data.message,/空间数量/);
  result=await request('/api/shiyu/auth/account','PUT',{userId:'u',data:[space('a')]});assert.equal(result.status,200);
  plans[0].entitlements.push(...['memo-limit','todo-limit','corner-limit','icon-daily-limit','color-daily-limit'].map(key=>({key,kind:'quantity',enabled:true,value:1})));
  result=await request('/api/shiyu/auth/tools','POST',{userId:'other',tool:'memo',revision:0,data:{notes:[]}});assert.equal(result.status,409);
  result=await request('/api/shiyu/auth/tools','POST',{userId:'u',tool:'memo',revision:0,data:{notes:[{id:'a'}]}});assert.equal(result.status,200);
  result=await request('/api/shiyu/auth/tools','POST',{userId:'u',tool:'memo',revision:1,data:{notes:[{id:'a'},{id:'b'}]}});assert.equal(result.status,409);assert.equal(result.data.code,'TOOL_QUOTA_EXCEEDED');
  result=await request('/api/shiyu/auth/tools');assert.equal(result.data.tools.memo.data.notes.length,1);
  const usage={userId:'u',tool:'icons',action:'reserve',requestId:'request-qa-1'};
  const concurrent=await Promise.all([request('/api/shiyu/auth/tool-usage','POST',usage),request('/api/shiyu/auth/tool-usage','POST',{...usage,requestId:'request-qa-2'})]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
  result=await request('/api/shiyu/auth/session');assert.equal(result.data.user.toolData,undefined);assert.equal(result.data.user.toolUsage,undefined);
  const anonymous=await fetch(base+'/api/shiyu/auth/tools');assert.equal(anonymous.status,401);
  const anonymousUsage=await fetch(base+'/api/shiyu/auth/tool-usage');assert.equal(anonymousUsage.status,200);assert.equal((await anonymousUsage.json()).userId,null);
});
