const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {choices}=JSON.parse(fs.readFileSync(path.join(__dirname,'palette-reference.json'),'utf8'));
const rgb=hex=>hex.match(/[a-f0-9]{2}/gi).map(x=>parseInt(x,16));
const mix=(a,b,amount)=>'#'+rgb(a).map((x,i)=>Math.round(x*amount+rgb(b)[i]*(1-amount)).toString(16).padStart(2,'0')).join('');
const luminance=hex=>rgb(hex).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
const cards=choices.map(({name,value,previous})=>{
  assert(luminance(value)>luminance(previous.value),name+' is brighter than current color');
  assert(contrast(value,'#17201b')>=4.5,name+' readable button label');
  const day=mix(value,'#ffffff',.2),night=mix(value,'#14171b',.13);
  assert(contrast(day,'#2d332d')>=4.5);assert(contrast(night,'#eeeee5')>=4.5);
  return `<article><div class="swatch" style="background:${value}"><b>${name}</b><code>${value.toUpperCase()}</code></div><div class="previous"><i style="background:${previous.value}"></i><span>现有配色</span><span>→ 更明亮</span></div><section style="background:${day};color:#2d332d"><small>日间背景</small><h3>让喜欢，自有归处</h3><div class="search" style="background:${mix(value,'#ffffff',.05)}">搜索喜欢的内容 <b style="background:${value};color:#17201b">↗</b></div></section><section style="background:${night};color:#eeeee5"><small>深色背景</small><h3>留一点柔和的光</h3><div class="search" style="background:${mix(value,'#20242a',.18)}">搜索喜欢的内容 <b style="background:${value};color:#17201b">↗</b></div></section></article>`;
}).join('');
// The proposal illustrates palette roles; it does not replace any application page.
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>拾隅柔和配色候选</title><style>*{box-sizing:border-box}body{margin:0;padding:48px 40px;background:#f6f7f9;color:#293239;font-family:'Microsoft YaHei',sans-serif}header{margin:0 0 30px}header p{margin:0 0 10px;color:#657179;font-size:12px;letter-spacing:2px}h1{font-size:29px;font-weight:600;margin:0 0 13px}header span{font-size:14px;color:#637077}.grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:14px}article{border-radius:18px;overflow:hidden;background:white;box-shadow:0 3px 20px #17202b06}.swatch{height:132px;padding:28px 20px;color:#17201b;display:flex;flex-direction:column;justify-content:space-between}.swatch b{font-size:17px;font-weight:600}code{font:12px Consolas,monospace;letter-spacing:1px}.previous{height:53px;display:flex;align-items:center;gap:7px;padding:0 13px;font-size:10px;color:#6c7479}.previous i{width:18px;height:18px;border-radius:50%;flex:none}.previous span:last-child{margin-left:auto}section{padding:24px 14px;height:174px}small{font-size:10px;letter-spacing:1px;opacity:.75}h3{font-size:13px;font-weight:500;margin:22px 0 17px}.search{font-size:9px;border-radius:9px;padding:8px;display:flex;align-items:center;justify-content:space-between}.search b{width:25px;height:25px;border-radius:7px;display:grid;place-items:center;font-size:15px}footer{margin-top:25px;display:flex;justify-content:space-between;color:#747d83;font-size:11px;line-height:1.9}footer b{font-weight:500;color:#4d585f}</style><header><p>SHIYU / COLOR STUDY</p><h1>更明亮，也更柔和。</h1><span>七种日间基础色 · 深色模式保留相同色相，降低背景亮度</span></header><div class="grid">${cards}</div><footer><span>色值参考：Radix Colors · Mint / Sage / Amber / Sky / Iris / Orange / Pink<br>日夜背景沿用拾隅现有派生方式；文字与按钮前景色单独保证清晰。</span><b>本地配色方案 · 尚未应用到线上</b></footer></html>`;
fs.writeFileSync(path.join(__dirname,'preview.html'),html);
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1470,height:800},deviceScaleFactor:1});await page.goto('file:///'+path.join(__dirname,'preview.html').replaceAll('\\','/'));await page.screenshot({path:path.join(__dirname,'preview.png'),fullPage:true});console.log('PASS: all 7 candidates are brighter; sample text and button contrast checked; preview rendered.')}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
