import {scheduleControl} from './trial-schedule.js';
const host=document.querySelector('#trial-placeholder');
const preview=location.protocol.startsWith('http'), api=window.trialApi;let revision=0,accountId=null,loadSerial=0;
const today=()=>new Date().toLocaleDateString('sv-SE');
let data;
if(!data?.memos||!data?.tasks)data={memos:[{id:'sample-note',content:'在拾隅，给喜欢的网址一个归处。\n也给一闪而过的灵感，留一个小小角落。',updated:Date.now()}],tasks:[{id:'sample-task',title:'在拾隅收藏第一个喜欢的网址',date:today(),priority:'普通',done:false}]};
if(preview)data.groups??=[{id:'work',name:'工作'},{id:'study',name:'学习'},{id:'life',name:'生活'}];
if(!preview)data={memos:[],tasks:[],groups:[]};
let app='memo',filter='all',query='',editing=null;
const completedOpen=new Map();
const groupSort=new Map();
function inGroup(task){return filter==='inbox'?!task.groupId||!data.groups.some(g=>g.id===task.groupId):task.groupId===filter;}
function sortTasks(items){const time=(a,b)=>{if(!a.date||!b.date)return Number(!!a.date)-Number(!!b.date);return a.date.localeCompare(b.date)||(a.start??-1)-(b.start??-1)};return items.sort((a,b)=>Number(!!a.done)-Number(!!b.done)||(groupSort.get(filter)==='priority'?priorities.indexOf(b.priority)-priorities.indexOf(a.priority)||time(a,b):time(a,b)));}

const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n};
const priorities=['普通','低优先级','中优先级','高优先级'];
function accept(result,tool){revision=result.revision;const d=result.data;if(tool==='memo')data.memos=(d.notes||[]).filter(x=>!x.deletedAt).map(x=>({...x,updated:x.updatedAt}));else {data.groups=(d.calendarV2?.groups||d.groups||[]).filter(g=>!g.system&&!g.deletedAt).map(g=>({id:g.id,name:g.name}));data.tasks=(d.calendarV2?.tasks||d.tasks||[]).filter(x=>!x.deletedAt).map(x=>({...x,priority:priorities[x.priority]||'普通'}))}}
async function loadRecords(){const serial=++loadSerial,tool=app;accountId=api.getState()?.accountId;host.replaceChildren(el('p','正在读取账号记录…'));try{const result=await api.call('tool-records',{payload:{tool,action:'read',accountId}});if(serial!==loadSerial||accountId!==api.getState()?.accountId)return;accept(result,tool);render()}catch(e){if(serial!==loadSerial)return;host.replaceChildren(el('p',e.message));const retry=el('button','重新加载','primary');retry.onclick=loadRecords;host.append(retry)}}
async function save(item){if(preview){status.textContent='示例已更新，刷新后恢复，不会同步账号';return true}try{if(!accountId||accountId!==api.getState()?.accountId)throw Error('账号已切换，请重新打开');const tool=app,owner=accountId;const result=await api.call('tool-records',{payload:{tool,action:'save',accountId:owner,revision,item:{...item,priority:priorities.indexOf(item.priority)}}});if(owner!==api.getState()?.accountId||tool!==app)return false;accept(result,tool);status.textContent='已同步到账号';return true}catch(e){status.textContent=e.message;return false}}
const status=el('p','','record-status');status.setAttribute('role','status');
function render(){host.replaceChildren();host.className='record-panel';const memo=app==='memo';if(!memo&&filter!=='inbox'&&!data.groups.some(g=>g.id===filter))filter='inbox';
 const form=el('form',null,'record-compose');const input=el(memo?'textarea':'input');input.placeholder=memo?'此刻想记下什么？':'添加一件要做的事';input.setAttribute('aria-label',memo?'小记内容':'待办内容');input.required=true;input.maxLength=memo?300:200;if(memo)input.rows=3;
 const current=(memo?data.memos:data.tasks).find(x=>x.id===editing);input.value=current?.content||current?.title||'';form.append(input);
 const controls=el('div',null,'record-controls');let date,priority;
 if(!memo){date=scheduleControl(current||{date:''});priority=el('select');priority.setAttribute('aria-label','优先级');['普通','低优先级','中优先级','高优先级'].forEach(s=>priority.add(new Option(s,s)));priority.value=current?.priority||'普通';controls.append(date.button,priority)}
 if(editing){const cancel=el('button','取消');cancel.type='button';cancel.onclick=()=>{editing=null;render()};controls.append(cancel)}
 const submit=el('button',editing?'保存修改':memo?'记下来':'添加待办','record-primary');submit.type='submit';controls.append(submit);form.append(controls);form.onsubmit=async e=>{e.preventDefault();const value=input.value.trim();if(!value)return;const item=current?{...current}:{id:crypto.randomUUID()};if(memo)Object.assign(item,{content:value,updated:Date.now()});else Object.assign(item,{title:value,groupId:current?.groupId||(filter==='inbox'?'':filter),...date.value,priority:priority.value,done:current?.done||false});submit.disabled=true;if(preview){const items=memo?data.memos:data.tasks;if(current)Object.assign(current,item);else items.unshift(item)}const ok=await save(item);submit.disabled=false;if(ok){editing=null;query='';render()}};host.append(form);
 const search=el('input',null,'record-search');search.type='search';search.placeholder=memo?'搜索小记':'搜索待办';search.setAttribute('aria-label',search.placeholder);search.value=query;
 const toolbar=el('div',null,'module-toolbar');const tabs=el('div',null,'record-tabs');tabs.setAttribute('aria-label',memo?'小记范围':'待办范围');(memo?[['all','小记'],['archive','归档']]:[['inbox','收集箱'],...data.groups.map(g=>[g.id,g.name])]).forEach(([id,name])=>{const button=el('button',name);button.setAttribute('aria-pressed',String(filter===id));button.onclick=()=>{filter=id;editing=null;render()};tabs.append(button)});const searchBox=el('form',null,'module-search');const searchButton=el('button',null,'module-search-button');searchButton.type='submit';searchButton.setAttribute('aria-label',memo?'搜索小记':'搜索待办');searchButton.title='搜索';searchButton.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 4.5 4.5"/></svg>';searchBox.append(search,searchButton);searchBox.onsubmit=e=>{e.preventDefault();query=search.value;results()};toolbar.append(tabs,searchBox);let sort;if(!memo){toolbar.classList.add('todo-toolbar');sort=el('button',null,'todo-sort');sort.type='button';const label=el('span');const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');icon.innerHTML='<path d="M8 19V5m-4 4 4-4 4 4M16 5v14m-4-4 4 4 4-4"/>';sort.append(label,icon);const updateSort=()=>{const byPriority=groupSort.get(filter)==='priority';label.textContent=byPriority?'按优先级排序':'按时间排序';sort.setAttribute('aria-label',label.textContent+'，点击切换为'+(byPriority?'按时间排序':'按优先级排序'));sort.title=sort.getAttribute('aria-label')};updateSort();sort.onclick=()=>{groupSort.set(filter,groupSort.get(filter)==='priority'?'time':'priority');updateSort();results()};}host.prepend(toolbar);form.hidden=memo&&filter==='archive';
 const list=el('div',null,'record-list');host.append(list,status);function results(){list.replaceChildren();let items=(memo?data.memos:data.tasks).filter(x=>(x.content||x.title).toLowerCase().includes(query.toLowerCase())&&(memo?(filter==='archive'?!!x.archivedAt:!x.archivedAt):inGroup(x)));if(!memo)items=sortTasks(items);if(memo&&!items.length)list.append(el('p','这里暂时没有记录。','record-empty'));let pending=list,completed=list;if(!memo){const unfinished=items.filter(x=>!x.done).length;const section=el('section',null,'todo-status-group');const heading=el('div',null,'todo-status-heading');heading.append(el('h3','未完成 · '+unfinished),sort);section.append(heading);pending=el('div',null,'todo-group-items');section.append(pending);list.append(section);if(!unfinished)pending.append(el('p',items.length?'当前范围内的事项已全部完成。':'这里暂时没有记录。','record-empty'));const doneCount=items.length-unfinished;if(doneCount){const details=el('details',null,'todo-completed');details.open=completedOpen.get(filter)||false;details.append(el('summary','已完成 · '+doneCount));completed=el('div',null,'todo-group-items');details.append(completed);const currentFilter=filter;details.ontoggle=()=>completedOpen.set(currentFilter,details.open);list.append(details)}}items.forEach(x=>{const card=el('article',null,'record-card'+(x.done?' is-done':''));if(!memo){const checkbox=el('input');checkbox.type='checkbox';checkbox.checked=x.done;checkbox.setAttribute('aria-label',`${x.done?'恢复':'完成'} ${x.title}`);checkbox.onchange=async()=>{checkbox.disabled=true;const next={...x,done:checkbox.checked};if(preview)x.done=next.done;const ok=await save(next);if(ok)render();else{checkbox.checked=x.done;checkbox.disabled=false}};card.append(checkbox)}const body=el('div',null,'record-body');body.append(el('p',x.content||x.title));body.append(el('small',memo?new Date(x.updated).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):`${x.date||'未安排时间'} · ${x.priority}`));const edit=el('button','编辑','record-edit');edit.onclick=()=>{if(memo){editMemo(body,x);return}editing=x.id;render();host.querySelector('.record-compose textarea,.record-compose>input').focus()};if(!memo||!x.archivedAt)body.append(edit);card.append(body);if(memo&&!x.archivedAt){card.classList.add('memo-editable-card');card.tabIndex=0;card.setAttribute('aria-label','小记，点击编辑');card.onclick=e=>{if(!e.target.closest('button,textarea,input'))editMemo(body,x)};card.onkeydown=e=>{if(e.target===card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();editMemo(body,x)}}}(memo?list:x.done?completed:pending).append(card)})}search.oninput=()=>{query=search.value;results()};results();}
for(const b of document.querySelectorAll('[data-app]'))b.addEventListener('click',()=>{app=b.dataset.app;filter=app==='memo'?'all':'inbox';query='';editing=null;status.textContent='';if(preview)render();else void loadRecords()});

document.addEventListener('trial-auth-change',()=>{if(document.body.dataset.auth!=='signed'){loadSerial++;accountId=null;if(!preview)data={memos:[],tasks:[],groups:[]}}else if(!preview&&!host.hidden)void loadRecords()});

function editMemo(body,item){if(body.querySelector('textarea'))return;const input=el('textarea');input.value=item.content;input.maxLength=300;input.rows=4;input.setAttribute('aria-label','编辑小记内容');const button=el('button','保存','record-primary'),message=el('p','','record-status');button.type='button';body.replaceChildren(input,button,message);body.classList.add('memo-inline-editor');let busy=false;
const outside=e=>{if(!body.isConnected){document.removeEventListener('pointerdown',outside);return}if(!body.contains(e.target)&&!e.target.closest('button,input,textarea,select,a,dialog'))void commit()};
async function commit(){if(busy)return;const content=input.value.trim();if(!content){message.textContent='请输入小记内容';return}if(content===item.content){document.removeEventListener('pointerdown',outside);render();return}busy=true;button.disabled=true;const next={...item,content,updated:Date.now()},old={...item};if(preview)Object.assign(item,next);const ok=await save(next);if(ok){document.removeEventListener('pointerdown',outside);if(body.isConnected)render()}else{if(preview)Object.assign(item,old);message.textContent=status.textContent;button.disabled=false;busy=false}}
button.onclick=commit;document.addEventListener('pointerdown',outside);input.focus();}
