const $=s=>document.querySelector(s),api=window.trialApi,preview=location.protocol.startsWith('http'),ext=globalThis.chrome;let rows=[],scope='all',selected=null,serial=0,owner=null,demoLoaded=false,windowId=null;
function options(id,items,label){const el=$(id);el.replaceChildren(new Option(label,''),...items.map(x=>new Option(x.name,x.id)))}
function spaces(){return api.getState()?.spaces||[]}
function filters(){options('#filter-space',spaces(),'全部空间');childFilters()}
function childFilters(){const s=spaces().find(x=>x.id===$('#filter-space').value);options('#filter-scene',s?.scenes||[],'全部场景');groupFilters()}
function groupFilters(){const c=spaces().find(x=>x.id===$('#filter-space').value)?.scenes.find(x=>x.id===$('#filter-scene').value);options('#filter-group',c?.groups||[],'全部分组');render()}
function text(tag,value){const el=document.createElement(tag);el.textContent=value;return el}
function render(){const q=$('#library-search').value.trim().toLowerCase();const groups=spaces().flatMap(s=>s.scenes.flatMap(c=>c.groups.map(g=>({key:[s.id,c.id,g.id].join('|'),name:g.name,path:[s.name,c.name,g.name].join(' / ')}))));if(scope==='all'||scope!=='inbox'&&!groups.some(g=>g.key===scope))scope=groups[0]?.key||'all';const found=rows.filter(x=>q?[x.title,x.url,x.description,x.path].some(v=>String(v||'').toLowerCase().includes(q)):scope==='inbox'?x.inbox:!x.inbox&&[x.spaceId,x.sceneId,x.groupId].join('|')===scope);$('.filters').hidden=true;$('.common-heading').textContent=q?'搜索全部网址':scope==='inbox'?'稍后整理':'常用网址';const tabs=$('.bottom-groups');tabs.replaceChildren(...[{key:'inbox',name:'稍后整理'},...groups].map(g=>{const b=text('button',g.name);b.dataset.scope=g.key;b.title=g.path||g.name;b.setAttribute('aria-pressed',String(scope===g.key));b.onclick=()=>{scope=g.key;$('#library-search').value='';render()};return b}));$('#search-summary').textContent=`${found.length} 个网址${q?' · 搜索结果':''}`;$('#search-results').replaceChildren(...found.map(x=>{const card=document.createElement('article');card.className='trial-card';const open=document.createElement('button');open.className='search-result';const mark=text('span',x.title.slice(0,1));mark.className='result-mark';const copy=document.createElement('span');copy.className='result-copy';copy.append(text('strong',x.title),text('small',x.domain),text('em',x.path));open.append(mark,copy,text('span','↗'));open.onclick=()=>{if(preview)window.open(x.url,'_blank','noopener');else api.call('open-url',{url:x.url}).catch(e=>$('#search-summary').textContent=e.message)};card.append(open);if(x.inbox){const move=text('button','归入分组');move.className='move-entry';move.onclick=()=>openMove(x);card.append(move)}return card}));if(!found.length)$('#search-results').append(text('p',q?'没有匹配的网址，试试清除筛选或更换关键词。':scope==='inbox'?'暂时没有待整理的网址。':'这里还没有网址。'));for(const b of document.querySelectorAll('[data-scope]')){b.setAttribute('aria-pressed',String(b.dataset.scope===scope));if(b.dataset.scope==='inbox')b.textContent='稍后整理 · '+rows.filter(x=>x.inbox).length}}
async function load(){if(preview&&demoLoaded){render();return}const n=++serial;$('#search-summary').textContent='正在读取…';try{const st=api.getState();if(!st?.signed){rows=[];render();return}const result=await api.call('list',{payload:{accountId:st.accountId}});if(n!==serial)return;owner=st.accountId;rows=result.items;demoLoaded=true;render()}catch(e){rows=[];$('#search-results').replaceChildren();$('#search-summary').textContent=e.message}}
function show(view){$('#trial-placeholder').hidden=true;api.setView(view);$('#view-title').textContent='拾隅';$('.bottom-groups').hidden=view!=='search';if(view==='search')void load();document.querySelectorAll('[data-app]').forEach(b=>b.setAttribute('aria-pressed','false'))}
function openMove(x){selected=x;options('#move-space',spaces(),'选择空间');$('#move-status').textContent='';moveScenes();$('#move-dialog').showModal()}
function moveScenes(){options('#move-scene',spaces().find(x=>x.id===$('#move-space').value)?.scenes||[],'选择场景');moveGroups()}
function moveGroups(){options('#move-group',spaces().find(x=>x.id===$('#move-space').value)?.scenes.find(x=>x.id===$('#move-scene').value)?.groups||[],'选择分组');$('#move-confirm').disabled=true}
$('#move-space').onchange=moveScenes;$('#move-scene').onchange=moveGroups;$('#move-group').onchange=()=>$('#move-confirm').disabled=!$('#move-group').value;$('#move-cancel').onclick=()=>$('#move-dialog').close();$('#move-confirm').onclick=async()=>{const b=$('#move-confirm');b.disabled=true;try{await api.call('move',{payload:{id:selected.id,accountId:owner,spaceId:$('#move-space').value,sceneId:$('#move-scene').value,groupId:$('#move-group').value}});if(preview){selected.inbox=false;selected.spaceId=$('#move-space').value;selected.sceneId=$('#move-scene').value;selected.groupId=$('#move-group').value;selected.path=[$('#move-space'),$('#move-scene'),$('#move-group')].map(x=>x.selectedOptions[0].text).join(' / ');render()}else await load();$('#move-dialog').close()}catch(e){$('#move-status').textContent=e.message}finally{b.disabled=!$('#move-group').value}};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>show(b.dataset.view);$('#library-search').oninput=render;$('#filter-space').onchange=()=>{childFilters();render()};$('#filter-scene').onchange=groupFilters;$('#filter-group').onchange=render;for(const b of document.querySelectorAll('[data-scope]'))b.onclick=()=>{scope=b.dataset.scope;render()};$('#clear-filters').onclick=()=>{filters();$('#library-search').value='';render()};
for(const b of document.querySelectorAll('[data-app]'))b.onclick=()=>{api.setView('search');$('#search-panel').hidden=true;$('.bottom-groups').hidden=true;$('#trial-placeholder').hidden=false;$('#trial-placeholder h2').textContent=b.dataset.app==='memo'?'小记':'待办';$('#view-title').textContent='拾隅';document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed','false'));document.querySelectorAll('[data-app]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))};$('#back-library').onclick=()=>show('search');
const opening=$('#opening');opening.onchange=async()=>{if(preview){document.body.classList.toggle('side-panel',opening.value==='side');return}try{if(opening.value==='side'){if(!ext.sidePanel?.open)throw Error('当前浏览器不支持侧边栏，请使用浮框。');await ext.sidePanel.open({windowId})}await ext.storage.local.set({opening:opening.value});$('#search-summary').textContent='默认展开方式已保存，下次点击插件图标生效。'}catch(e){opening.value='popup';$('#status').textContent=e.message;$('#search-summary').textContent=e.message}};
async function init(){while(!document.body.dataset.ready)await new Promise(r=>setTimeout(r,50));filters();$('#version-status').textContent='V0.3.0';$('#version-status').onclick=null;if(preview){$('#trial-note').textContent='布局预览 · 示例数据，操作不会改动真实收藏';}else{windowId=(await ext.windows.getCurrent()).id;opening.value=(await ext.storage.local.get('opening')).opening||'popup';window.addEventListener('focus',async()=>{await api.connect();filters();if(!$('#search-panel').hidden)await load()});}if(!document.querySelector('[data-app][aria-pressed=true]')){if(document.body.classList.contains('side-panel')){opening.value='side';show('search')}else show('bookmark')}document.body.dataset.trialReady='true'}
void init();

for(const b of document.querySelectorAll('[data-opening]'))b.onclick=async()=>{opening.value=b.dataset.opening;await opening.onchange();syncModes()};function syncModes(){for(const b of document.querySelectorAll('[data-opening]'))b.setAttribute('aria-pressed',String(b.dataset.opening===opening.value))}setTimeout(syncModes,300);

// All trial modules share the extension's verified account state.
const gateMessage=document.createElement('p');gateMessage.setAttribute('role','status');
const gateRetry=document.createElement('button');gateRetry.className='primary';gateRetry.textContent='重新校验登录状态';gateRetry.onclick=()=>api.connect();
$('#login-panel').append(gateMessage,gateRetry);
function syncAccountGate(){const auth=document.body.dataset.auth||'checking';const signed=auth==='signed';$('#login-panel').hidden=signed;gateMessage.textContent=auth==='checking'?'正在校验登录状态…':auth==='error'?'暂时无法确认登录状态，请重试。':preview?'当前为网页预览。请安装试用插件以读取拾隅登录状态。':'登录后即可使用收藏、常用、小记和待办。';gateRetry.hidden=auth!=='error';$('#login').hidden=auth==='checking'||auth==='error';if(!signed){serial++;rows=[];demoLoaded=false;$('#search-results').replaceChildren();$('#trial-placeholder').hidden=true;$('#move-dialog').close();}document.querySelectorAll('[data-view],[data-app]').forEach(b=>b.disabled=!signed);}
document.addEventListener('trial-auth-change',syncAccountGate);syncAccountGate();
document.addEventListener('click',e=>{if(document.body.dataset.auth!=='signed'&&e.target.closest('[data-view],[data-app],#bookmark-form,#search-panel,#trial-placeholder,#move-dialog')){e.preventDefault();e.stopImmediatePropagation();}},true);
