const {chromium,request}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const front='http://127.0.0.1:4319',admin='http://127.0.0.1:5185',out=__dirname;
const isolate=async(ctx)=>{await ctx.route('https://cdn.jsdelivr.net/**',r=>r.abort());await ctx.route('**/api/shiyu/auth/wechat/qr**',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'测试环境未启用微信'})}))};
const login=async(ctx,who)=>{const r=await ctx.request.post(front+'/api/shiyu/auth/login',{data:{account:'avatar-'+who+'@example.invalid',credential:'avatar-local-check',mode:'password'}});assert.equal(r.status(),200,await r.text())};
(async()=>{fs.copyFileSync('../聚合管理后台/shiyu-avatar-seed.json','.local/avatar-catalog-qa/avatars.json');const fixture=JSON.parse(fs.readFileSync('.local/avatar-catalog-qa/users.json','utf8'));fixture.items.forEach((u,i)=>{u.avatarProfile={avatarId:'',gender:i?'female':'male'};u.accountData=[{id:'work',name:'测试空间',scenes:[{id:'daily',name:'日常',groups:[]}]}]});fs.writeFileSync('.local/avatar-catalog-qa/users.json',JSON.stringify(fixture));const browser=await chromium.launch({channel:'msedge',headless:true}),results={};try{
 const adminCtx=await browser.newContext({viewport:{width:1440,height:1050}});let r=await adminCtx.request.post(admin+'/api/platform/login',{data:{account:'admin',password:'123456'}});assert.equal(r.status(),200,await r.text());
 const adminPage=await adminCtx.newPage();await adminPage.goto(admin+'/apps/shiyu/avatars');await adminPage.locator('.avatar-art-card').last().waitFor();assert.equal(await adminPage.locator('.avatar-art-card').count(),32);await adminPage.evaluate(()=>document.querySelectorAll('.avatar-art-card img').forEach(img=>img.loading='eager'));await adminPage.waitForFunction(()=>[...document.querySelectorAll('.avatar-art-card img')].every(i=>i.complete&&i.naturalWidth>0));await adminPage.screenshot({path:path.join(out,'admin-gallery.png'),fullPage:true});await adminPage.locator('.avatar-art-card').first().hover();await adminPage.waitForFunction(()=>getComputedStyle(document.querySelector('.avatar-art-caption')).opacity==='1');await adminPage.screenshot({path:path.join(out,'admin-hover.png')});await adminPage.getByRole('button',{name:'修改 蓝调书生',exact:true}).click();await adminPage.getByRole('textbox',{name:'头像名称',exact:true}).fill('蓝调书生·测试');await adminPage.waitForTimeout(400);await adminPage.screenshot({path:path.join(out,'admin-edit.png')});await adminPage.locator('.ant-drawer-footer .ant-btn-primary').click();await adminPage.getByRole('dialog').waitFor({state:'hidden'});
 r=await adminCtx.request.get(admin+'/api/shiyu/avatars');let catalog=(await r.json()).items;assert.equal(catalog.find(x=>x.id==='male-blue-scholar').name,'蓝调书生·测试');results.rename=true;
 await adminCtx.request.put(admin+'/api/shiyu/avatars/male-blue-scholar',{data:{name:'蓝调书生'}});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await isolate(ctx);await login(ctx,'a');
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>{if(!e.message.includes('not in whitelist')&&!e.message.includes('测试环境未启用微信'))errors.push(e.message)});
 await page.addInitScript(()=>localStorage.setItem('shiyu-account-profile:avatar-qa-a',JSON.stringify({name:'头像验证A',gender:'male',profileCompleted:true})));
 await page.goto(front,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.ShiyuAvatars&&typeof accountProfile==='function'&&accountProfile().id==='avatar-qa-a');await page.evaluate(()=>openAccountCenter());await page.locator('[data-profile-avatar-open]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-avatar-choice]').length===16);await page.evaluate(()=>ShiyuAvatars.cacheReady());await page.waitForFunction(()=>[...document.querySelectorAll('[data-avatar-choice] img')].every(i=>i.naturalWidth>0));await page.evaluate(()=>Promise.all([...document.querySelectorAll('[data-avatar-choice] img')].map(i=>i.decode())));await page.waitForTimeout(600);await page.screenshot({path:path.join(out,'picker-male.png')});
 await page.locator('[data-avatar-choice="male-blue-scholar"]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('shiyu-avatar-selection-v1:avatar-qa-a')||'{}').pending===false);r=await ctx.request.get(front+'/api/shiyu/auth/avatar');assert.equal((await r.json()).profile.avatarId,'male-blue-scholar');results.accountSaved=true;
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof accountProfile==='function'&&accountProfile().avatar==='catalog:male-blue-scholar');await page.waitForFunction(()=>document.querySelector('.account-entry img')?.naturalWidth>0);results.reload=true;
 await ctx.setOffline(true);await page.evaluate(()=>ShiyuAvatars.open());await page.waitForFunction(()=>document.querySelectorAll('[data-avatar-choice]').length===16);await page.waitForFunction(()=>document.querySelector('[data-avatar-choice="male-crimson-rider"] img')?.naturalWidth>0);await page.locator('[data-avatar-choice="male-crimson-rider"]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('shiyu-avatar-selection-v1:avatar-qa-a')).pending===true);assert(await page.evaluate(()=>document.querySelector('.account-entry img').src.startsWith('blob:')&&document.querySelector('.account-entry img').naturalWidth>0));results.offlinePngAndPending=true;await page.screenshot({path:path.join(out,'offline-avatar.png')});
 await ctx.setOffline(false);await page.evaluate(()=>dispatchEvent(new Event('online')));await page.waitForFunction(()=>JSON.parse(localStorage.getItem('shiyu-avatar-selection-v1:avatar-qa-a')).pending===false);r=await ctx.request.get(front+'/api/shiyu/auth/avatar');assert.equal((await r.json()).profile.avatarId,'male-crimson-rider');results.reconnect=true;
 const device=await browser.newContext({viewport:{width:390,height:844}});await isolate(device);await login(device,'a');const second=await device.newPage();await second.goto(front,{waitUntil:'domcontentloaded'});await second.waitForFunction(()=>typeof accountProfile==='function'&&accountProfile().avatar==='catalog:male-crimson-rider');results.otherDevice=true;
 await login(device,'b');await second.evaluate(()=>window.refreshShiyuMembership(true));await second.waitForFunction(()=>accountProfile().id==='avatar-qa-b'&&accountProfile().gender==='female');assert.notEqual(await second.evaluate(()=>accountProfile().avatar),'catalog:male-crimson-rider');await second.evaluate(()=>ShiyuAvatars.open());await second.waitForFunction(()=>document.querySelectorAll('[data-avatar-choice]').length===16);assert.equal(await second.locator('[data-avatar-choice^="male-"]').count(),0);await second.waitForFunction(()=>[...document.querySelectorAll('[data-avatar-choice] img')].every(i=>i.naturalWidth>0));await second.evaluate(()=>ShiyuAvatars.cacheReady());await second.evaluate(()=>Promise.all([...document.querySelectorAll('[data-avatar-choice] img')].map(i=>i.decode())));await second.waitForTimeout(500);await second.screenshot({path:path.join(out,'picker-female-mobile.png')});assert(await second.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));results.accountIsolation=true;
 await second.locator('[data-avatar-close]').click();await second.evaluate(()=>ShiyuAvatars.changeGender('private'));await second.evaluate(()=>ShiyuAvatars.open());await second.waitForFunction(()=>document.querySelectorAll('[data-avatar-choice]').length===32);results.unknownAll=true;
 const bad=await device.request.put(front+'/api/shiyu/auth/avatar',{data:{userId:'avatar-qa-a',avatarId:'male-blue-scholar',gender:'private'}});assert.equal(bad.status(),409);const upload=await device.request.put(front+'/api/shiyu/auth/avatar',{data:{userId:'avatar-qa-b',avatarId:'data:image/png;base64,abc',gender:'private'}});assert.equal(upload.status(),400);results.noUserUpload=true;
 r=await adminCtx.request.delete(admin+'/api/shiyu/avatars/male-crimson-rider');assert.equal(r.status(),200);await page.evaluate(()=>ShiyuAvatars.refresh());await page.evaluate(()=>ShiyuAvatars.open());await page.waitForFunction(()=>!document.querySelector('[data-avatar-choice="male-crimson-rider"]'));assert.equal(await page.evaluate(()=>accountProfile().avatar),'catalog:male-crimson-rider');assert(await page.evaluate(()=>document.querySelector('.account-entry img').naturalWidth>0));results.deletedRetainsChosen=true;

 // Upload, replace and remove through the visual admin UI, isolated from real data.
 await adminPage.locator('input[type=file]').setInputFiles('../聚合管理后台/public/shiyu-avatars/male-blue-scholar.png');
 await adminPage.getByRole('textbox',{name:'头像名称',exact:true}).fill('上传验证头像');
 await adminPage.locator('.ant-drawer-footer .ant-btn-primary').click();await adminPage.getByRole('dialog').waitFor({state:'hidden'});
 let created=(await (await adminCtx.request.get(admin+'/api/shiyu/avatars')).json()).items.find(x=>x.name==='上传验证头像');assert(created?.imageUrl);
 const bytes=await (await ctx.request.get(front+created.imageUrl)).body();assert(bytes.equals(fs.readFileSync('../聚合管理后台/public/shiyu-avatars/male-blue-scholar.png')));results.uploadTransparentPng=true;
 await adminPage.getByRole('button',{name:'替换 上传验证头像',exact:true}).click({force:true});
 await adminPage.locator('input[type=file]').setInputFiles('../聚合管理后台/public/shiyu-avatars/male-crimson-rider.png');
 await adminPage.locator('.ant-drawer-footer .ant-btn-primary').click();await adminPage.getByRole('dialog').waitFor({state:'hidden'});
 const replaced=(await (await adminCtx.request.get(admin+'/api/shiyu/avatars')).json()).items.find(x=>x.id===created.id);assert.notEqual(replaced.imageUrl,created.imageUrl);assert.equal(replaced.name,'上传验证头像');results.replace=true;
 await adminPage.getByRole('button',{name:'删除 上传验证头像',exact:true}).click({force:true});await adminPage.locator('.ant-popconfirm-buttons .ant-btn-primary').click();await adminPage.locator('.avatar-art-card[aria-label="男生头像 上传验证头像"]').waitFor({state:'detached'});results.visualDelete=true;
 await adminPage.getByRole('radiogroup').getByText('女生',{exact:true}).click();await adminPage.waitForFunction(()=>document.querySelectorAll('.avatar-art-card').length===16);await adminPage.evaluate(()=>document.querySelectorAll('.avatar-art-card img').forEach(i=>i.loading='eager'));await adminPage.evaluate(()=>Promise.all([...document.querySelectorAll('.avatar-art-card img')].map(i=>i.decode())));await adminPage.screenshot({path:path.join(out,'admin-female.png')});
 const anonymous=await request.newContext();r=await anonymous.post(admin+'/api/shiyu/avatars',{data:{name:'入侵'}});assert.equal(r.status(),403);await anonymous.dispose();results.adminGuard=true;
 results.pageErrors=errors;assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
