from pathlib import Path
p=Path('dist/extension/integration.js')
s=p.read_text(encoding='utf-8')
s=s.replace("laterTab='temporary'","laterTab='archive'").replace("const laterCategory=x=>x.category==='archive'?'archive':'temporary';","const laterCategory=x=>x.category==='temporary'?'temporary':'archive';\n  const laterSymbol=id=>svgIcon(id==='archive'?'<rect x=\"4\" y=\"3\" width=\"16\" height=\"18\" rx=\"3\"/><path d=\"M8 8h8M8 12h5M8 16h3\"/>':'<path d=\"m3 9 3-5h12l3 5v11H3Z\"/><path d=\"M3 10h5l2 3h4l2-3h5\"/>');")
s=s.replace("laterAccount=store.snapshot().accountId;laterChosen.clear();", "laterAccount=store.snapshot().accountId;laterTab='archive';laterChosen.clear();")
s=s.replace("laterDrawer.addEventListener('click',e=>{if(e.target===laterDrawer)","laterDrawer.addEventListener('cancel',e=>{const target=laterDrawer.querySelector('.later-archive-target');if(target&&!target.hidden){e.preventDefault();hideLaterTarget();}});\n      laterDrawer.addEventListener('click',e=>{const target=laterDrawer.querySelector('.later-archive-target');if(target&&!target.hidden&&!e.target.closest('.later-archive-target,[data-later-archive]')){hideLaterTarget();if(e.target===laterDrawer)return;}if(e.target===laterDrawer)")
s=s.replace("  function drawLaterDrawer(){", "  function hideLaterTarget(){const target=laterDrawer.querySelector('.later-archive-target');if(!target)return;target.hidden=true;target.querySelectorAll('.select-options').forEach(x=>x.hidden=true);target.querySelectorAll('.select-trigger').forEach(x=>x.setAttribute('aria-expanded','false'));laterDrawer.querySelector('[data-later-archive]')?.setAttribute('aria-expanded','false');}\n  function drawLaterDrawer(){")
s=s.replace("[['temporary','临时留存'],['archive','留待归档']]", "[['archive','待整理'],['temporary','已整理']]")
s=s.replace('${name}<small>${all.filter', '${laterSymbol(id)}<span>${name}</span><small>${all.filter')
s=s.replace('aria-label="关闭稍后管理">×', 'aria-label="关闭稍后管理">${svgIcon(\'<path d="m6 6 12 12M18 6 6 18"/>\')}')
s=s.replace('移至留待归档','移至待整理').replace('移至临时留存','移至已整理').replace('还没有留待归档的网址','还没有待整理的网址')
s=s.replace('${svgIcon(\'<path d="M4 7h16m-4-4 4 4-4 4M20 17H4m4-4-4 4 4 4"/>\')}', '${laterSymbol(laterTab===\'temporary\'?\'archive\':\'temporary\')}')
s=s.replace("action==='clear'?'已清除 '+result.count+' 项':'已移动'", "action==='clear'?'已清除 '+result.count+' 项':'已移至'+(extra.category==='temporary'?'已整理':'待整理')")
s=s.replace('class="later-archive-target" hidden','class="later-archive-target" id="later-archive-popover" role="group" aria-label="选择归档位置" hidden')
s=s.replace('data-later-archive>归档到…','data-later-archive aria-controls="later-archive-popover" aria-expanded="false">归档到…')
s=s.replace("target.hidden=!target.hidden;", "if(!target.hidden){hideLaterTarget();return;}target.hidden=false;laterDrawer.querySelector('[data-later-archive]').setAttribute('aria-expanded','true');")
p.write_text(s,encoding='utf-8')
p=Path('dist/extension/store.js');s=p.read_text(encoding='utf-8').replace("inbox.unshift({ id: crypto.randomUUID(), item, createdAt: Date.now() });","inbox.unshift({ id: crypto.randomUUID(), item, category: 'archive', createdAt: Date.now() });");p.write_text(s,encoding='utf-8')
