
const {chromium}=require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:960}});const errors=[];p.on('pageerror',e=>errors.push(e.message));let config=await(await fetch('http://127.0.0.1:4337/api/shiyu/operations')).json();assert(config.corner.modules.some(m=>m.id==='toolbox'));
await p.route('**/api/shiyu/operations',r=>r.fulfill({json:config}));await p.route('**/api/shiyu/auth/**',r=>r.fulfill({status:r.request().url().includes('/wechat/')?200:503,json:{}}));
async function open(){await p.goto('http://127.0.0.1:4337/');await p.evaluate(()=>{prefs.theme='base';prefs.mode='light';render()});await p.waitForSelector('#corner-orbit-demo[data-theme-ready=true]');const core=p.frameLocator('#corner-orbit-demo').locator('.core');const rect=await core.boundingBox();await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await p.frameLocator('#corner-orbit-demo').locator('.stage.is-filled').waitFor();await p.waitForTimeout(800);}
await open();const frame=p.frameLocator('#corner-orbit-demo');assert.equal(await frame.locator('.menu-item:not([hidden])').count(),4);await p.screenshot({path:'.local/toolbox-20260926/menu.png'});await frame.locator('.menu-item').filter({hasText:'百宝箱'}).click();await p.waitForFunction(()=>document.querySelector('#toast')?.textContent==='敬请期待'||[...document.querySelectorAll('.toast')].some(e=>e.textContent==='敬请期待'));assert.equal(await p.locator('#login[open],#my-corner[open]').count(),0);
const selected=await frame.locator('.menu-item.is-selected').evaluate(el=>{const r=el.getBoundingClientRect(),s=el.closest('.stage').getBoundingClientRect();return {x:r.x+r.width/2-s.x-s.width/2,y:r.y+r.height/2-s.y-s.height/2}});assert(Math.abs(selected.x)<2&&selected.y<0);
config.corner.modules.find(m=>m.id==='toolbox').enabled=false;await open();assert.equal(await frame.locator('.menu-item:not([hidden])').count(),3);
Object.assign(config.corner.modules.find(m=>m.id==='toolbox'),{enabled:true,entryName:'工具箱测试',icon:'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLz4='});await open();assert.equal(await frame.locator('.menu-item').filter({hasText:'工具箱测试'}).locator('img').count(),1);assert.deepEqual(errors,[]);console.log('PASS four entries, selected stays top, guest click toast, remote disable/name/icon sync');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
