const { chromium } = require('C:/Users/任伟的机械革命/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
const assert = require('node:assert/strict')

;(async () => {
  const config = await (await fetch('http://127.0.0.1:4337/api/shiyu/operations')).json()
  config.corner.modules.push({ id: 'palette-maker', enabled: true, entryName: '配色工具', panelName: '配色工具', icon: '', category: '设计工具', description: '临时配置的扩展示例', href: 'http://127.0.0.1:4173/#home' })
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 960 } })
    page.setDefaultTimeout(8000)
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.addInitScript(() => localStorage.setItem('yiyu-prototype-v1', JSON.stringify({ signed: true, prefs: { accountProfile: { id: 'toolbox-check' } } })))
    await page.route('**/api/**', route => route.fulfill({ status: 200, json: route.request().url().includes('/api/shiyu/operations') ? config : {} }))

    await page.goto('http://127.0.0.1:4337/', { waitUntil: 'domcontentloaded' })
    await page.waitForSelector('#corner-orbit-demo[data-theme-ready="true"]')
    const frame = page.frameLocator('#corner-orbit-demo')
    const core = frame.locator('.core')
    const coreBox = await core.boundingBox()
    await page.mouse.move(coreBox.x + coreBox.width / 2, coreBox.y + coreBox.height / 2)
    await frame.locator('.stage.is-filled').waitFor()
    await page.waitForTimeout(700)
    assert.equal(await frame.locator('.menu-item:not([hidden])').count(), 4)
    assert.equal(await frame.locator('.menu-item').count(), 8, 'home fan has room for seven pinned tools plus Toolbox')
    const selected = await frame.locator('.menu-item.is-selected:not([hidden])').evaluate(el => {
      const item = el.getBoundingClientRect(), stage = el.closest('.stage').getBoundingClientRect()
      return { x: item.x + item.width / 2 - stage.x - stage.width / 2, y: item.y + item.height / 2 - stage.y - stage.height / 2 }
    })
    assert(selected.y < 0, 'selected item stays on the upper half of the 180° fan')

    await page.goto('http://127.0.0.1:4337/?corner=toolbox', { waitUntil: 'domcontentloaded' })
    await page.locator('.corner-tool-row').nth(4).waitFor()
    assert.equal(await page.locator('.corner-tool-row').count(), 5)
    assert.deepEqual(await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => row.querySelectorAll('[data-corner-open-tool]').length)), [24, 24, 24, 24, 24], 'each tilted row repeats the full catalog for seamless looping')
    const eightRows = await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => [...row.querySelectorAll('[data-corner-open-tool]')].slice(0, 8).map(card => card.dataset.cornerOpenTool)))
    assert(eightRows.every((row, index) => row[0] === eightRows[0][Math.floor(index * 8 / 3) % 8]), 'each row starts one-third of the catalog after the previous row')
    const phases = await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => Number(row.dataset.toolPhase)))
    assert(Math.abs(phases[1] - 2 / 3) < .001 && Math.abs(phases[2] - 1 / 3) < .001 && phases[3] === 0, 'non-divisible catalog sizes retain the fractional card offset')
    assert.equal(await page.locator('.corner-tool-image').count(), 0, 'tool cards no longer use background images')
    for (const id of ['icons', 'palette', 'cutout', 'emoji']) assert.equal(await page.locator(`.corner-tool-card[data-tool-card="${id}"] .tool-art`).count(), 15, `${id} uses the copied home-card artwork in every loop`)
    for (const id of ['common', 'memo', 'todo']) assert.equal(await page.locator(`.corner-tool-card[data-tool-card="${id}"] .tool-art`).count(), 15, `${id} has its own animated artwork`)
    assert.equal(await page.locator('.corner-tool-card .corner-tool-copy').evaluateAll(copies => copies.filter(copy => copy.children.length !== 1 || copy.firstElementChild?.tagName !== 'STRONG').length), 0, 'each card shows only its configured title')
    assert.equal(await page.locator('.corner-tool-pin,[data-corner-pin]').count(), 0, 'Toolbox has no pin or favorite control')
    assert.equal(await page.locator('.corner-toolbox-heading,.corner-toolbox-note,#my-corner .dialog-heading:visible').count(), 0, 'toolbox has no title or footer overlay')
    const gridSize = await page.locator('.corner-tool-grid').evaluate(el => ({ width: parseFloat(getComputedStyle(el).width), height: parseFloat(getComputedStyle(el).height), gap: getComputedStyle(el).gap }))
    assert.equal(gridSize.width, 2880, 'grid width matches the reference at 200vw')
    assert.equal(gridSize.height, 1536, 'large card rows leave only parts of the outer rows visible')
    assert.equal(gridSize.gap, '8px', 'horizontal and vertical card gaps are equal')
    assert.equal(await page.locator('.corner-tool-row').first().evaluate(row => getComputedStyle(row).gap), '8px', 'spacing within each row matches spacing between rows')
    assert(await page.locator('.corner-tool-row').evaluateAll(rows => rows.every(row => row.firstElementChild?.offsetHeight === row.offsetHeight)), 'legacy grid positioning does not shrink lower-row cards')
    await page.screenshot({ path: '.local/toolbox-home-cards-light.png' })
    const iconCards = page.locator('.corner-tool-card[data-tool-card="icons"]')
    const visibleIcon = await iconCards.evaluateAll(cards => cards.map((card, index) => { const box = card.getBoundingClientRect(), left = Math.max(0, box.left), right = Math.min(innerWidth, box.right), top = Math.max(0, box.top), bottom = Math.min(innerHeight, box.bottom); return { index, area: Math.max(0, right - left) * Math.max(0, bottom - top), x: (left + right) / 2, y: (top + bottom) / 2 } }).sort((a, b) => b.area - a.area)[0])
    assert(visibleIcon.area > 10000, 'the copied icon card appears in the viewport')
    const iconArt = iconCards.nth(visibleIcon.index).locator('.icons-art>span:first-child')
    const iconBefore = await iconArt.evaluate(el => getComputedStyle(el).transform)
    await page.mouse.move(visibleIcon.x, visibleIcon.y)
    await page.waitForTimeout(750)
    assert.notEqual(await iconArt.evaluate(el => getComputedStyle(el).transform), iconBefore, 'source icon artwork animates on hover')
    for (const [id, selector] of [['common', '.common-sheet-front'], ['memo', '.memo-page'], ['todo', '.todo-row-one']]) {
      const cards = page.locator(`.corner-tool-card[data-tool-card="${id}"]`)
      const visible = await cards.evaluateAll(items => items.map((item, index) => { const box = item.getBoundingClientRect(), left = Math.max(0, box.left), right = Math.min(innerWidth, box.right), top = Math.max(0, box.top), bottom = Math.min(innerHeight, box.bottom); return { index, area: Math.max(0, right - left) * Math.max(0, bottom - top), x: (left + right) / 2, y: (top + bottom) / 2 } }).sort((a, b) => b.area - a.area)[0])
      assert(visible.area > 10000, `${id} card is reachable in the viewport`)
      await page.mouse.move(20, 20)
      await page.waitForTimeout(700)
      const art = cards.nth(visible.index).locator(selector)
      const beforeArt = await art.evaluate(el => getComputedStyle(el).transform)
      const tile = cards.nth(visible.index).locator('.corner-tool-open')
      const beforeTile = await tile.evaluate(el => ({ box: el.getBoundingClientRect().toJSON(), background: getComputedStyle(el).backgroundImage }))
      const arrow = cards.nth(visible.index).locator('.corner-tool-arrow')
      assert.equal(await arrow.evaluate(el => getComputedStyle(el).borderTopWidth), '0px', 'hover arrow has no surrounding circle')
      await page.mouse.move(visible.x, visible.y)
      await page.waitForTimeout(750)
      assert.notEqual(await art.evaluate(el => getComputedStyle(el).transform), beforeArt, `${id} artwork responds to hover`)
      assert.equal(await arrow.evaluate(el => getComputedStyle(el).opacity), '1', 'a small arrow appears on hover')
      const afterTile = await tile.evaluate(el => ({ box: el.getBoundingClientRect().toJSON(), background: getComputedStyle(el).backgroundImage }))
      assert(Math.abs(afterTile.box.x - beforeTile.box.x) < .1 && Math.abs(afterTile.box.y - beforeTile.box.y) < .1, 'the full card stays in place on hover')
      assert.equal(afterTile.background, beforeTile.background, 'hover preserves the card color family')
    }
    const firstRow = page.locator('.corner-tool-row').first()
    const before = await firstRow.evaluate(el => getComputedStyle(el).transform)
    await page.locator('.corner-toolbox-scroll').dispatchEvent('wheel', { deltaY: 2000, deltaMode: 0 })
    await page.waitForTimeout(100)
    const inertiaStart = await firstRow.evaluate(el => getComputedStyle(el).transform)
    const rowTransforms = await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => getComputedStyle(row).transform))
    assert(new Set(rowTransforms).size > 1, 'five rows move at slightly different speeds')
    const rowOffsets = await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => new DOMMatrix(getComputedStyle(row).transform).m41))
    assert(Math.abs(rowOffsets[0] - rowOffsets[4]) < 1 && Math.abs(rowOffsets[1] - rowOffsets[3]) < 1, 'rows above and below the center move symmetrically')
    assert(rowOffsets[2] < rowOffsets[1] && rowOffsets[1] < rowOffsets[0], 'center row advances fastest while scrolling')
    await page.waitForTimeout(650)
    assert.notEqual(await firstRow.evaluate(el => getComputedStyle(el).transform), before, 'wheel moves rows with easing')
    assert.notEqual(await firstRow.evaluate(el => getComputedStyle(el).transform), inertiaStart, 'outer row continues gliding after wheel input stops')
    await page.waitForTimeout(2800)
    const stoppedOffsets = await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => new DOMMatrix(getComputedStyle(row).transform).m41))
    assert(Math.max(...stoppedOffsets) - Math.min(...stoppedOffsets) < 1, 'all rows settle at the same final travel distance')
    assert.equal(new Set(await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => getComputedStyle(row).transform))).size, 1, 'every row uses the exact same offset when motion stops')
    await page.locator('.corner-toolbox-scroll').dispatchEvent('wheel', { deltaY: -15000, deltaMode: 0 })
    await page.waitForTimeout(1700)
    assert.notEqual(await firstRow.evaluate(el => getComputedStyle(el).transform), before, 'reverse scrolling continues through the loop')
    await page.waitForTimeout(1300)
    assert.equal(new Set(await page.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => getComputedStyle(row).transform))).size, 1, 'all rows realign after reverse scrolling across the loop')

    const paletteCards = page.locator('[data-corner-open-tool="palette-maker"]')
    let visiblePalette = -1
    for (let attempt = 0; attempt < 12 && visiblePalette < 0; attempt++) {
      visiblePalette = await paletteCards.evaluateAll(cards => cards.findIndex(card => { const box = card.getBoundingClientRect(); return box.left > 20 && box.right < innerWidth - 20 && box.top > 50 && box.bottom < innerHeight - 50 }))
      if (visiblePalette < 0) { await page.locator('.corner-toolbox-scroll').dispatchEvent('wheel', { deltaY: 480, deltaMode: 0 }); await page.waitForTimeout(260) }
    }
    assert(visiblePalette >= 0, 'custom tool card appears during looping scroll')
    await paletteCards.nth(visiblePalette).click()
    await page.locator('.corner-tool-cover-card').waitFor()
    assert(page.url().includes('corner=palette-maker'), 'tool route updates for refresh restoration')
    const popupWait = page.waitForEvent('popup')
    await page.locator('[data-corner-launch-tool="palette-maker"]').click()
    const popup = await popupWait
    await popup.waitForLoadState('domcontentloaded')
    assert(popup.url().includes('4173/#home'), 'tool opens in its separate application tab')
    await popup.close()
    await page.goto('http://127.0.0.1:4337/?corner=palette', { waitUntil: 'domcontentloaded' })
    await page.locator('[data-corner-launch-tool="palette"]').waitFor()
    const palettePopupWait = page.waitForEvent('popup')
    await page.locator('[data-corner-launch-tool="palette"]').click()
    const palettePopup = await palettePopupWait
    await palettePopup.waitForLoadState('domcontentloaded')
    assert(palettePopup.url().includes('4173/#palette'), 'the fourth home card opens its independent light-app route')
    await palettePopup.close()
    const sixConfig = structuredClone(config)
    sixConfig.corner.modules = sixConfig.corner.modules.filter(module => module.id !== 'palette-maker' && module.id !== 'palette')
    const sixPage = await browser.newPage({ viewport: { width: 1440, height: 960 } })
    await sixPage.addInitScript(() => localStorage.setItem('yiyu-prototype-v1', JSON.stringify({ signed: true, prefs: { accountProfile: { id: 'toolbox-six-check' } } })))
    await sixPage.route('**/api/**', route => route.fulfill({ status: 200, json: route.request().url().includes('/api/shiyu/operations') ? sixConfig : {} }))
    await sixPage.goto('http://127.0.0.1:4337/?corner=toolbox', { waitUntil: 'domcontentloaded' })
    await sixPage.locator('.corner-tool-row').nth(4).waitFor()
    await sixPage.waitForTimeout(100)
    const sixRows = await sixPage.locator('.corner-tool-row').evaluateAll(rows => rows.map(row => [...row.querySelectorAll('[data-corner-open-tool]')].map(card => card.dataset.cornerOpenTool)))
    assert(sixRows.every(row => row.length === 18 && row.every((id, index) => index === 0 || id !== row[index - 1])), 'six-tool rows loop without adjacent duplicates')
    assert.deepEqual(sixRows.map(row => row[0]), [sixRows[0][0], sixRows[0][2], sixRows[0][4], sixRows[0][0], sixRows[0][2]], 'six tools shift by two positions per row')
    await sixPage.screenshot({ path: '.local/toolbox-grid-qa.png' })
    await sixPage.close()
    assert.deepEqual(errors, [])
    console.log('PASS: title-only source-style tool cards, animated personal tools, eight-slot 180° home fan, five-row looping toolbox, wheel motion, route restore and independent app launch')
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
